name: Java Springboot Continuous Integration
on:
  push:
    branches: [main]
  pull_request
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
     uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
       java-version: '11'
       name: Build with Maven
        run: mvn clean install
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'
      - name: Run Tests
        run: mvn test
