name: Java Springboot Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   
   - name: Check code
     uses: actions/checkout@v4

   - name: Set up JDK11
     uses: actions/setup-java@v1
     with:
       java-version: '11'

   - name: Build with Maven
     run: mvn clean install

   - name: Build
     run: mvn clean install

   - name: Upload artifact for deployment job
     uses: actions/upload-artifact@v2
     with:
       name: java-app
       path: '${{ github.workspace }}/target/*.jar'

   - name: Run test
     run: mvn test
